### ISSUE TITLE
r2pipe TextIOWrapper error

### ISSUE THREAD

**Issue by GiuseppeLaurenza** [radare/radare2-r2pipe#34]
Hi,
updating radare2 to the last commit, now I have a TextIOWrapper error

> 'file' object has no attribute 'readable'

r2 -v

> radare2 2.2.0-git 16646 @ darwin-x86-64 git.2.1.0-62-g410ca0980
commit: 410ca098030e18f9cff00d49c45499fa33b4f1db build: 2017-12-04__10:40:40

pip freeze | grep r2pipe

> r2pipe==0.9.3

using r2 to analyze directly the file I have not any problem

**Comment by radare** [comment]
please @AlexKornitzer fix that regression was introduced by you in 7d6ab9bc9c72394e7219bb5d2ea98276605d34cd

**Comment by AlexKornitzer** [comment]
@radare on it. @GiuseppeLaurenza is this for python 2 or 3?

**Comment by GiuseppeLaurenza** [comment]
I use it with python2. I did not tested it with python3

**Comment by AlexKornitzer** [comment]
@GiuseppeLaurenza That will be the problem then I only tested it on Python 3, apologies. I will try and get a fix in this evening.

**Comment by AlexKornitzer** [comment]
@radare @GiuseppeLaurenza the PR above should fix the issue :)

**Comment by GiuseppeLaurenza** [comment]
@AlexKornitzer thanks for the fix,
sorry for the stupid question, how I can apply the fix? Usually I use pip to install r2pipe but I can use also git if you explain how to add this commit in the clone process

**Comment by AlexKornitzer** [comment]
Probably best to wait for @radare to push it to the pip repository. Otherwise you can directly modify the file to reflect that in the PR.

**Comment by GiuseppeLaurenza** [comment]
@AlexKornitzer ok thanks
@radare which will be the estimated time for the update of the pip package? Thanks in advance

**Comment by radare** [comment]
i have released 0.9.4, please test and close the issue if so :)

**Comment by radare** [comment]
now

**Comment by GiuseppeLaurenza** [comment]
problem is apparently solved with the fix, so I close the issue for now
Thanks @radare and @AlexKornitzer

**Comment by radare** [comment]
Awesome! Thanks @alexkornitzer

**Comment by AlexKornitzer** [comment]
@radare np, if you break it, you fix it :P
